import { PTA_MOBILE_TAX, REFERENCE_RATES } from "../data/rates";
import { num, str, type ToolDefinition } from "../types";
import { pkr } from "@/lib/format";

export const ptaMobileTaxCalculator: ToolDefinition = {
  slug: "pta-mobile-tax-calculator",
  category: "telecom",
  name: "PTA Mobile Tax Calculator",
  shortName: "PTA Tax",
  description: "Estimate the PTA/FBR tax to register an imported phone (iPhone, Samsung, any brand) on a passport or CNIC.",
  keywords: ["PTA tax", "PTA tax iPhone", "mobile registration tax", "DIRBS", "phone import duty pakistan", "PTA approved", "iPhone 17 PTA tax", "customs duty mobile"],
  version: "1.0.0",
  lastReviewed: PTA_MOBILE_TAX.reviewedAt,
  featured: true,
  sources: [PTA_MOBILE_TAX.source],
  fields: [
    { key: "valueUsd", label: "Phone value", type: "number", unit: "USD", default: 999, min: 1, step: 10, help: "Declared / market value in US dollars. Flagship phones are typically $700–$1,300." },
    {
      key: "doc",
      label: "Register using",
      type: "select",
      options: [
        { value: "passport", label: "Passport (within 60 days of arrival)" },
        { value: "cnic", label: "CNIC" },
      ],
      default: "passport",
    },
    { key: "usdPkr", label: "USD → PKR rate", type: "number", unit: "PKR", default: REFERENCE_RATES.usdPkr, min: 100, step: 0.5, help: "Used only for the sales-tax component on higher-value phones." },
  ],
  compute(input) {
    const valueUsd = num(input, "valueUsd");
    const doc = str(input, "doc", "passport") === "cnic" ? "cnic" : "passport";
    const usdPkr = num(input, "usdPkr", REFERENCE_RATES.usdPkr);
    const slabs = PTA_MOBILE_TAX[doc];
    const slab = slabs.find((s) => s.maxUsd === null || valueUsd <= s.maxUsd) ?? slabs[slabs.length - 1];
    const valuePkr = valueUsd * usdPkr;
    const pctPart = valuePkr * slab.pctOfValue;
    const total = slab.fixedPkr + pctPart;
    const other = PTA_MOBILE_TAX[doc === "cnic" ? "passport" : "cnic"];
    const otherSlab = other.find((s) => s.maxUsd === null || valueUsd <= s.maxUsd) ?? other[other.length - 1];
    const otherTotal = otherSlab.fixedPkr + valuePkr * otherSlab.pctOfValue;

    return {
      headline: { label: `PTA tax on ${doc === "cnic" ? "CNIC" : "passport"}`, value: pkr(total), primary: true },
      summary: `A $${valueUsd.toLocaleString()} phone (≈ ${pkr(valuePkr)}) falls in the ${slab.maxUsd ? `up to $${slab.maxUsd}` : "above $500"} slab. Registering on ${doc === "cnic" ? "passport instead would cost " : "CNIC instead would cost "}${pkr(otherTotal)}.`,
      sections: [
        {
          title: "Breakdown",
          lines: [
            { label: "Fixed duty & taxes for slab", value: pkr(slab.fixedPkr) },
            ...(slab.pctOfValue > 0 ? [{ label: `Sales tax (${Math.round(slab.pctOfValue * 100)}% of ${pkr(valuePkr)})`, value: pkr(pctPart) }] : []),
            { label: "Total payable", value: pkr(total), primary: true },
          ],
        },
        {
          title: "Compare",
          lines: [
            { label: "On passport", value: pkr(doc === "passport" ? total : otherTotal) },
            { label: "On CNIC", value: pkr(doc === "cnic" ? total : otherTotal) },
          ],
        },
      ],
      warnings: [
        "Indicative estimate. The exact amount is generated by PTA DIRBS / FBR when you apply and can differ by model valuation.",
        "Passport rates apply only if the phone is registered within 60 days of your arrival in Pakistan.",
      ],
    };
  },
  methodology: `PTA requires every phone used on Pakistani networks for more than 120 days (one-time 120-day free use per passport) to be registered through **DIRBS**. FBR collects customs duty, regulatory duty, sales tax, withholding tax and mobile levy as a **single consolidated amount** determined by the phone's declared value in USD.

The schedule has **fixed amounts per value slab**; slabs above $200 also add sales tax on the phone's value. Rates are lower when registering on a **passport within 60 days of arrival** than on a CNIC.

This tool applies the slab table published for the current fiscal year. The review date shows when Searchable last verified it.`,
  faqs: [
    { question: "Can I use a phone without paying PTA tax?", answer: "A foreign phone works for 120 days per passport entry without registration. After that, non-registered devices are blocked on all Pakistani networks." },
    { question: "Is the tax different for iPhone and Android?", answer: "No — it depends on the phone's value, not the brand. Higher-value phones pay more." },
    { question: "How do I pay?", answer: "Apply on the DIRBS portal or by SMS to 8484, receive a PSID, and pay at a bank, ATM, or through a banking app." },
    { question: "Does dual-SIM cost more?", answer: "Each IMEI is registered; a dual-SIM phone has two IMEIs but is treated as one device with a single payment." },
  ],
  related: { tools: ["income-tax-calculator"], guides: ["how-to-register-phone-with-pta"], entities: ["pta", "fbr", "apple"], businessCategories: ["mobile-shops"] },
};
