/**
 * SAMPLE businesses for the local prototype. Not seeded in SEED_MODE=reference.
 * Names are illustrative; phone numbers are placeholders.
 */
export type BusinessDef = {
  slug: string;
  name: string;
  category: string;
  city: string;
  area?: string;
  tagline?: string;
  description: string;
  address: string;
  phone?: string;
  whatsapp?: string;
  website?: string;
  priceRange?: number;
  verified?: boolean;
  tier?: "free" | "verified" | "premium" | "sponsored";
  rating?: [number, number];
  hours?: [string, string] | "24h";
  services?: string[];
  entities?: string[];
};

export const BUSINESSES: BusinessDef[] = [
  // ── Lahore ──
  { slug: "bundu-khan-lahore", name: "Bundu Khan", category: "restaurants", city: "lahore", area: "mall-road", tagline: "Lahore's classic barbecue since 1948", description: "Charcoal-grilled seekh kababs, tikkas and Lahori breakfast. Family seating, takeaway and delivery.", address: "Mall Road, near Regal Chowk, Lahore", phone: "042-111-000-101", whatsapp: "0300-0000101", priceRange: 2, verified: true, tier: "verified", rating: [4.3, 412], hours: ["11:00", "23:30"], services: ["Dine-in", "Takeaway", "Delivery", "Family hall"] },
  { slug: "butt-karahi-lahore", name: "Butt Karahi", category: "restaurants", city: "lahore", area: "gulberg", tagline: "Desi ghee karahi, weighed by the kilo", description: "Mutton and chicken karahi cooked to order in desi ghee; large portions meant for sharing.", address: "Main Boulevard, Gulberg III, Lahore", phone: "042-111-000-102", priceRange: 3, verified: true, tier: "premium", rating: [4.5, 890], hours: ["12:00", "01:00"], services: ["Dine-in", "Takeaway", "Outdoor seating"] },
  { slug: "cafe-aylanto-lahore", name: "Café Aylanto", category: "restaurants", city: "lahore", area: "gulberg", tagline: "Mediterranean dining in Gulberg", description: "Fine-dining Mediterranean and continental menu, quiet ambience, good for business lunches.", address: "12-C, Main Boulevard, Gulberg III, Lahore", phone: "042-111-000-103", priceRange: 4, verified: false, rating: [4.4, 230], hours: ["12:30", "23:30"], services: ["Dine-in", "Reservations", "Private dining"] },
  { slug: "sunrise-solar-lahore", name: "Sunrise Solar Solutions", category: "solar-companies", city: "lahore", area: "johar-town", tagline: "Net-metered rooftop systems from 3 kW to 50 kW", description: "Tier-1 panels, hybrid and on-grid inverters, complete net-metering paperwork with LESCO. Free site survey in Lahore.", address: "Block G-1, Johar Town, Lahore", phone: "042-111-000-201", whatsapp: "0321-0000201", website: "https://example.com/sunrise-solar", priceRange: 3, verified: true, tier: "premium", rating: [4.6, 148], hours: ["09:00", "18:00"], services: ["5 kW on-grid system", "10 kW hybrid system", "Net-metering application", "Annual maintenance"], entities: ["solar-energy", "lesco", "nepra"] },
  { slug: "greenvolt-energy-lahore", name: "GreenVolt Energy", category: "solar-companies", city: "lahore", area: "dha-lahore", tagline: "Solar for homes in DHA and Cantt", description: "Residential solar specialist with financing partnerships with Meezan Bank and HBL.", address: "Sector Y, DHA Phase 3, Lahore", phone: "042-111-000-202", whatsapp: "0333-0000202", priceRange: 3, verified: true, tier: "verified", rating: [4.4, 96], hours: ["10:00", "19:00"], services: ["Site survey", "Bank financing", "Battery backup", "Net metering"], entities: ["solar-energy", "meezan-bank"] },
  { slug: "tax-desk-associates-lahore", name: "TaxDesk Associates", category: "tax-consultants", city: "lahore", area: "gulberg", tagline: "NTN, returns, wealth statements: done in 48 hours", description: "Chartered accountants handling salaried and business tax returns, NTN registration, sales tax and FBR notices.", address: "Office 4, 2nd Floor, Gulberg II, Lahore", phone: "042-111-000-301", whatsapp: "0300-0000301", priceRange: 2, verified: true, tier: "verified", rating: [4.7, 64], hours: ["10:00", "18:00"], services: ["Salaried tax return: Rs 5,000", "Business tax return: from Rs 15,000", "NTN registration: Rs 2,000", "Sales tax registration"], entities: ["fbr", "income-tax"] },
  { slug: "doctors-hospital-lahore", name: "Doctors Hospital & Medical Center", category: "hospitals", city: "lahore", area: "johar-town", description: "Private tertiary-care hospital with 24/7 emergency, cardiology, oncology and a large OPD.", address: "152-G/1, Canal Bank, Johar Town, Lahore", phone: "042-111-000-401", priceRange: 3, verified: true, tier: "verified", rating: [4.1, 1020], hours: "24h", services: ["Emergency", "Cardiology", "Oncology", "Maternity", "Lab & radiology"] },
  { slug: "dr-ayesha-khan-dermatologist-lahore", name: "Dr Ayesha Khan: Dermatologist", category: "doctors", city: "lahore", area: "dha-lahore", tagline: "MBBS, FCPS (Dermatology)", description: "Consultant dermatologist: acne, pigmentation, hair loss, laser treatments. Evening clinic in DHA.", address: "Clinic 7, CCA Block, DHA Phase 5, Lahore", phone: "042-111-000-402", whatsapp: "0321-0000402", priceRange: 3, verified: false, rating: [4.8, 57], hours: ["17:00", "21:00"], services: ["Consultation: Rs 3,000", "Laser hair removal", "Chemical peel"] },
  { slug: "toyota-ravi-motors-lahore", name: "Toyota Ravi Motors", category: "car-dealers", city: "lahore", area: "wapda-town", description: "Authorised Toyota 3S dealership: new Corolla, Yaris, Fortuner and Hilux sales, service and spare parts.", address: "Main Multan Road, near WAPDA Town, Lahore", phone: "042-111-000-501", website: "https://example.com/ravi-motors", priceRange: 4, verified: true, tier: "verified", rating: [4.2, 340], hours: ["09:00", "18:00"], services: ["New car sales", "Bank financing", "Service & parts", "Trade-in"], entities: ["toyota"] },
  { slug: "hafeez-centre-mobile-mall-lahore", name: "Hafeez Centre: Mobile Zone", category: "mobile-shops", city: "lahore", area: "gulberg", tagline: "Lahore's biggest phone market", description: "Hundreds of shops for new and used phones, PTA-approved and non-PTA units, repairs and accessories.", address: "Hafeez Centre, Main Boulevard, Gulberg III, Lahore", phone: "042-111-000-601", priceRange: 2, verified: false, rating: [4.0, 2100], hours: ["11:00", "22:00"], services: ["New phones", "Used phones", "PTA registration help", "Repairs"], entities: ["pta", "apple", "samsung"] },
  { slug: "quick-fix-electricians-lahore", name: "QuickFix Electricians", category: "electricians", city: "lahore", area: "model-town", description: "Same-day home electrical work: wiring, UPS/inverter installation, fault finding, AC points.", address: "Model Town Link Road, Lahore", phone: "0300-0000701", whatsapp: "0300-0000701", priceRange: 1, verified: true, tier: "free", rating: [4.5, 88], hours: ["08:00", "22:00"], services: ["Home visit: Rs 1,500", "UPS installation", "Wiring & rewiring"] },
  { slug: "fitness-first-dha-lahore", name: "Fitness First DHA", category: "gyms", city: "lahore", area: "dha-lahore", description: "Full-floor gym with cardio, free weights, ladies' hours and personal training.", address: "Sector C, DHA Phase 6, Lahore", phone: "042-111-000-801", priceRange: 3, verified: false, rating: [4.3, 210], hours: ["06:00", "23:00"], services: ["Monthly: Rs 8,000", "Personal training", "Ladies' timings"] },
  { slug: "pearl-continental-lahore", name: "Pearl-Continental Lahore", category: "hotels", city: "lahore", area: "mall-road", description: "Five-star hotel on Mall Road with conference facilities and multiple restaurants.", address: "Shahrah-e-Quaid-e-Azam (Mall Road), Lahore", phone: "042-111-000-901", website: "https://example.com/pc-lahore", priceRange: 4, verified: true, tier: "verified", rating: [4.5, 3100], hours: "24h", services: ["Rooms", "Conference halls", "Restaurants", "Airport transfer"] },

  // ── Karachi ──
  { slug: "kolachi-do-darya-karachi", name: "Kolachi Restaurant", category: "restaurants", city: "karachi", area: "dha-karachi", tagline: "Seafront dining at Do Darya", description: "Large open-air restaurant on the Arabian Sea: barbecue, karahi and seafood.", address: "Do Darya, DHA Phase 8, Karachi", phone: "021-111-000-101", priceRange: 3, verified: true, tier: "premium", rating: [4.4, 5200], hours: ["17:00", "02:00"], services: ["Dine-in", "Outdoor seating", "Events"] },
  { slug: "burns-road-food-street-karachi", name: "Burns Road Food Street", category: "restaurants", city: "karachi", area: "saddar", tagline: "Karachi's oldest food street", description: "Nihari, haleem, bun kabab, rabri and dozens of legacy eateries in one lane.", address: "Burns Road, Saddar, Karachi", priceRange: 1, verified: false, rating: [4.6, 8800], hours: ["12:00", "02:00"], services: ["Street food", "Takeaway"] },
  { slug: "aga-khan-university-hospital-karachi", name: "Aga Khan University Hospital", category: "hospitals", city: "karachi", area: "gulshan-e-iqbal", description: "JCI-accredited tertiary hospital with the country's largest outpatient network.", address: "Stadium Road, Karachi", phone: "021-111-000-201", website: "https://example.com/akuh", priceRange: 4, verified: true, tier: "verified", rating: [4.6, 4100], hours: "24h", services: ["Emergency", "All specialties", "Lab collection points citywide"] },
  { slug: "solarwise-karachi", name: "SolarWise Pakistan", category: "solar-companies", city: "karachi", area: "gulistan-e-johar", tagline: "K-Electric net metering specialists", description: "Rooftop solar for Karachi homes and shops, with K-Electric net-metering processing included.", address: "Block 13, Gulistan-e-Johar, Karachi", phone: "021-111-000-301", whatsapp: "0345-0000301", priceRange: 3, verified: true, tier: "verified", rating: [4.5, 122], hours: ["10:00", "19:00"], services: ["3 kW system", "5 kW hybrid", "10 kW commercial", "KE net metering"], entities: ["solar-energy", "k-electric"] },
  { slug: "clifton-legal-chambers-karachi", name: "Clifton Legal Chambers", category: "lawyers", city: "karachi", area: "clifton", description: "Corporate, property and family law. Registered with Sindh High Court.", address: "Block 5, Clifton, Karachi", phone: "021-111-000-401", priceRange: 3, verified: true, tier: "verified", rating: [4.7, 41], hours: ["10:00", "18:00"], services: ["Property transfer", "Company registration (SECP)", "Family law", "Corporate advisory"], entities: ["secp"] },
  { slug: "honda-south-karachi", name: "Honda South", category: "car-dealers", city: "karachi", area: "dha-karachi", description: "Authorised Honda 3S dealer: City, Civic, BR-V and HR-V.", address: "Main Korangi Road, DHA Phase 1, Karachi", phone: "021-111-000-501", priceRange: 4, verified: true, tier: "verified", rating: [4.1, 260], hours: ["09:00", "18:00"], services: ["New car sales", "Financing", "Service"], entities: ["honda"] },
  { slug: "star-city-mobile-mall-karachi", name: "Star City Mall: Mobile Market", category: "mobile-shops", city: "karachi", area: "saddar", description: "Karachi's main mobile wholesale and retail hub in Saddar.", address: "Star City Mall, Saddar, Karachi", priceRange: 2, verified: false, rating: [4.1, 1500], hours: ["11:00", "22:00"], services: ["New phones", "Used phones", "Accessories", "Repairs"], entities: ["pta"] },
  { slug: "the-city-school-dha-karachi", name: "The City School: DHA Campus", category: "schools", city: "karachi", area: "dha-karachi", description: "Cambridge-affiliated school, playgroup to A Levels.", address: "Phase 6, DHA, Karachi", phone: "021-111-000-601", priceRange: 3, verified: false, rating: [4.0, 190], hours: ["07:30", "14:30"], services: ["Playgroup–A Levels", "Transport"] },
  { slug: "meezan-bank-clifton-branch-karachi", name: "Meezan Bank: Clifton Branch", category: "banks", city: "karachi", area: "clifton", description: "Full-service Islamic banking branch with car Ijarah and home finance desks.", address: "Block 4, Clifton, Karachi", phone: "021-111-000-701", priceRange: 2, verified: true, tier: "verified", rating: [4.2, 130], hours: ["09:00", "17:00"], services: ["Accounts", "Car Ijarah", "Home finance", "Roshan Digital Account"], entities: ["meezan-bank"] },
  { slug: "smile-dental-clinic-karachi", name: "Smile Dental Clinic", category: "dentists", city: "karachi", area: "bahadurabad", description: "General and cosmetic dentistry, implants, braces. Evening appointments.", address: "Bahadurabad Chowrangi, Karachi", phone: "021-111-000-801", whatsapp: "0300-0000801", priceRange: 2, verified: false, rating: [4.7, 76], hours: ["15:00", "22:00"], services: ["Check-up: Rs 1,500", "Scaling", "Braces", "Implants"] },

  // ── Islamabad ──
  { slug: "monal-islamabad", name: "The Monal", category: "restaurants", city: "islamabad", tagline: "Dinner with a view of the capital", description: "Hilltop restaurant in the Margalla Hills with Pakistani and continental menus.", address: "Pir Sohawa Road, Margalla Hills, Islamabad", phone: "051-111-000-101", priceRange: 3, verified: true, tier: "verified", rating: [4.3, 6000], hours: ["12:00", "00:00"], services: ["Dine-in", "Outdoor seating", "Events"] },
  { slug: "khiva-restaurant-islamabad", name: "Khiva Restaurant", category: "restaurants", city: "islamabad", area: "f-7", description: "Uzbek and Central Asian cuisine: plov, manti, shashlik.", address: "Jinnah Super, F-7 Markaz, Islamabad", phone: "051-111-000-102", priceRange: 3, verified: false, rating: [4.5, 1400], hours: ["12:00", "23:00"], services: ["Dine-in", "Takeaway"] },
  { slug: "shifa-international-hospital-islamabad", name: "Shifa International Hospital", category: "hospitals", city: "islamabad", area: "i-8", description: "JCI-accredited private hospital with transplant, cardiac and cancer centres.", address: "Pitras Bukhari Road, H-8/4, Islamabad", phone: "051-111-000-201", priceRange: 4, verified: true, tier: "verified", rating: [4.3, 2200], hours: "24h", services: ["Emergency", "Cardiology", "Transplant", "Oncology"] },
  { slug: "capital-solar-islamabad", name: "Capital Solar", category: "solar-companies", city: "islamabad", area: "g-11", tagline: "IESCO net metering in 30 days", description: "Residential and commercial solar across Islamabad and Rawalpindi. Longi and Jinko panels, Inverex and Solis inverters.", address: "G-11 Markaz, Islamabad", phone: "051-111-000-301", whatsapp: "0333-0000301", priceRange: 3, verified: true, tier: "premium", rating: [4.6, 210], hours: ["09:00", "18:00"], services: ["5 kW: from Rs 650,000", "10 kW: from Rs 1,200,000", "IESCO net metering", "Maintenance"], entities: ["solar-energy", "nepra"] },
  { slug: "fbr-tax-facilitation-islamabad", name: "Rehman & Co. Tax Advisors", category: "tax-consultants", city: "islamabad", area: "blue-area", description: "Tax and corporate advisory for individuals and SMEs; FBR audits and appeals.", address: "Jinnah Avenue, Blue Area, Islamabad", phone: "051-111-000-401", priceRange: 2, verified: true, tier: "verified", rating: [4.6, 38], hours: ["10:00", "18:00"], services: ["Tax return filing", "NTN & STRN", "Audit representation", "Company registration"], entities: ["fbr", "secp"] },
  { slug: "islamabad-mobile-mall-blue-area", name: "Islamabad Mobile Mall", category: "mobile-shops", city: "islamabad", area: "blue-area", description: "PTA-approved and imported phones, accessories, repairs.", address: "Blue Area, Islamabad", phone: "051-111-000-501", priceRange: 2, verified: false, rating: [4.0, 420], hours: ["11:00", "22:00"], services: ["New phones", "PTA-approved stock", "Repairs"], entities: ["pta"] },
  { slug: "toyota-capital-motors-islamabad", name: "Toyota Capital Motors", category: "car-dealers", city: "islamabad", area: "i-8", description: "Authorised Toyota dealership serving Islamabad and Rawalpindi.", address: "I-9 Industrial Area, Islamabad", phone: "051-111-000-601", priceRange: 4, verified: true, tier: "verified", rating: [4.2, 300], hours: ["09:00", "18:00"], services: ["New car sales", "Financing", "Service"], entities: ["toyota"] },
  { slug: "serena-hotel-islamabad", name: "Islamabad Serena Hotel", category: "hotels", city: "islamabad", description: "Five-star hotel near the Diplomatic Enclave with gardens and event spaces.", address: "Khayaban-e-Suhrawardy, Islamabad", phone: "051-111-000-701", priceRange: 4, verified: true, tier: "verified", rating: [4.7, 2800], hours: "24h", services: ["Rooms", "Banquets", "Spa", "Restaurants"] },
  { slug: "pixel-studio-photographers-islamabad", name: "Pixel Studio", category: "photographers", city: "islamabad", area: "f-10", description: "Wedding and corporate photography, drone coverage, same-week delivery.", address: "F-10 Markaz, Islamabad", phone: "0300-0000801", whatsapp: "0300-0000801", priceRange: 2, verified: false, rating: [4.8, 66], hours: ["10:00", "20:00"], services: ["Wedding package: from Rs 150,000", "Corporate events", "Drone"] },

  // ── Other cities ──
  { slug: "rawalpindi-solar-hub", name: "Pindi Solar Hub", category: "solar-companies", city: "rawalpindi", area: "satellite-town", description: "Affordable solar packages for Rawalpindi homes.", address: "Satellite Town, Rawalpindi", phone: "051-111-000-901", priceRange: 2, verified: false, rating: [4.2, 54], hours: ["09:00", "19:00"], services: ["3 kW package", "5 kW package"], entities: ["solar-energy"] },
  { slug: "peshawar-namak-mandi-charsi-tikka", name: "Charsi Tikka: Namak Mandi", category: "restaurants", city: "peshawar", description: "Peshawar's most famous lamb tikka and karahi, cooked over coal in Namak Mandi.", address: "Namak Mandi, Peshawar", priceRange: 2, verified: false, rating: [4.6, 3300], hours: ["12:00", "01:00"], services: ["Dine-in", "Takeaway"] },
  { slug: "faisalabad-chenab-tax-consultants", name: "Chenab Tax Consultants", category: "tax-consultants", city: "faisalabad", description: "Tax and sales-tax compliance for Faisalabad's textile SMEs.", address: "D Ground, Faisalabad", phone: "041-111-000-101", priceRange: 2, verified: false, rating: [4.4, 22], hours: ["10:00", "18:00"], services: ["Sales tax returns", "Income tax returns", "Export refunds"], entities: ["fbr"] },
  { slug: "quetta-sajji-house", name: "Lehri Sajji House", category: "restaurants", city: "quetta", description: "Whole-lamb sajji roasted over open fire: Quetta's signature dish.", address: "Jinnah Road, Quetta", priceRange: 2, verified: false, rating: [4.5, 900], hours: ["12:00", "23:00"], services: ["Dine-in", "Takeaway"] },
];
